apiVersion: networking.gloo.solo.io/v2
kind: VirtualGateway
metadata:
  name: north-south-gw
  namespace: istio-gateways
spec:
  listeners:
    - http: {}
      port:
        number: 443
      tls:
        mode: SIMPLE
        secretName: tls-secret