apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: bookinfo
  namespace: bookinfo-frontends
spec:
  options:
    serviceIsolation:
      enabled: true
      trimProxyConfig: true