apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- petstore-v1.yaml
- petstore-v2.yaml
- petstore-openapi-v1-pets-apidoc.yaml 
- petstore-openapi-v1-users-apidoc.yaml
- petstore-openapi-v2-full-apidoc.yaml
- petstore-apiproduct.yaml    
#- dev-environment.yaml
- dev-environment-wplan.yaml
#- petstore-portal.yaml
- petstore-portal-wstatic.yaml
- default-petstore-portal-faq-cm.yaml
#- developer-group.yaml
- developer-group-wplan.yaml
- developer1-user.yaml
- developer1-password.yaml