apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: keycloak-http-vs
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /keycloak/
      options:
        prefixRewrite: /auth/
      routeAction:
        single:
          upstream:
            name: default-keycloak-8080
            namespace: gloo-system
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: default-keycloak-8080
            namespace: gloo-system