##################################################################################################
# Ratings service
##################################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-ratings
  labels:
    account: ratings
